# Generated by Django 5.0.8 on 2024-08-25 15:03

import blog.models
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_comment_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish_at', 'title']},
        ),
        migrations.AlterField(
            model_name='post',
            name='post_photo',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=blog.models.imageUpload_post_image, variations={'large': (600, 400), 'medium': (300, 200), 'thumbnail': (100, 100, True)}, verbose_name='Main Image'),
        ),
    ]
