# Generated by Django 5.0.8 on 2024-08-25 12:22

import stdimage.models
import user_profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_remove_profile_first_name_remove_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=user_profiles.models.imageUpload_main, variations={'large': (600, 400), 'medium': (300, 200), 'thumbnail': (100, 100, True)}, verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='main_photo',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to=user_profiles.models.imageUpload_main, variations={'large': (600, 400), 'medium': (300, 200), 'thumbnail': (100, 100, True)}, verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Work'),
        ),
    ]
